// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaUUQCOxm5u3Bb5e63qVF8Vxq0-eXjND0',
    appId: '1:627680208796:web:16584b87d5523a3bff8a59',
    messagingSenderId: '627680208796',
    projectId: 'instagramclone-bb3f7',
    authDomain: 'instagramclone-bb3f7.firebaseapp.com',
    storageBucket: 'instagramclone-bb3f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWiZaPcKdkOWEkELl3G80HPvxlpyBnx9k',
    appId: '1:627680208796:android:8766f30735609bdfff8a59',
    messagingSenderId: '627680208796',
    projectId: 'instagramclone-bb3f7',
    storageBucket: 'instagramclone-bb3f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHjFbUuyxz0hBfs1twcJL6hAF7iLtcnM',
    appId: '1:627680208796:ios:98794e27932d633cff8a59',
    messagingSenderId: '627680208796',
    projectId: 'instagramclone-bb3f7',
    storageBucket: 'instagramclone-bb3f7.appspot.com',
    androidClientId: '627680208796-59elpe2sbhioj4jjl7pphqbdncggurnf.apps.googleusercontent.com',
    iosClientId: '627680208796-92he09b2b50gav8loppfd3l0eom8d15n.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );
}
